name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
        
env:
  image_url: wanghsinche/name-pls
  docker_username: wanghsinche

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login Registry
      run: |
        docker login --username=${{ env.docker_username }} --password=${{ secrets.DOCKER_PASSWORD }}

    - run: npm install
    - run: npm run build
    - name: Build the Docker image
      run: docker build . --tag ${{ env.image_url }}:$(date +%s)
    
        
    - name: Publish
      run: |
        docker push ${{ env.image_url }}

    
